footer:
- name: Chat
  url: https://chat.dashdevs.org
- name: Bounties
  url: https://bounties.dashdevs.org
- name: Github
  url: https://github.com/andyfreer/awesome-dash-platform
- name: Get Listed
  url: https://github.com/andyfreer/awesome-dash-platform/blob/master/CONTRIBUTING.md
- name: Dash.org
  url: https://dash.org
